[package]
name = "rust-ssh-connect"
version = "0.1.0"
authors = ["taky <taky@taky.com>"]
description = "attempt ssh connections with various configurations"

[dependencies]
ssh2 = "0.9"
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
dirs = "4.0"
